"use client";

import type { Dispatch, ReactNode, SetStateAction } from "react";

import { Button } from "@/components/ui/button";
import { Card, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { Profile } from "@/lib/api";

const lines = (value: string) => value.split("\n").filter((item) => item.trim());
const csv = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);

export function ProfileEditor({ draft, setDraft }: { draft: Profile; setDraft: Dispatch<SetStateAction<Profile>> }) {
  const patch = (next: Partial<Profile>) => setDraft((current) => ({ ...current, ...next }));
  const update = <K extends keyof Profile>(key: K, index: number, value: Record<string, unknown>) => {
    const list = draft[key] as unknown as Array<Record<string, unknown>>;
    patch({ [key]: list.map((item, itemIndex) => itemIndex === index ? { ...item, ...value } : item) } as Partial<Profile>);
  };
  const add = <K extends keyof Profile>(key: K, value: object) => patch({ [key]: [...(draft[key] as unknown as object[]), value] } as Partial<Profile>);
  const remove = <K extends keyof Profile>(key: K, index: number) => patch({ [key]: (draft[key] as unknown as unknown[]).filter((_, itemIndex) => itemIndex !== index) } as Partial<Profile>);
  return <div className="space-y-8">
    <section className="space-y-3"><CardTitle>Basics</CardTitle><div className="grid gap-3 sm:grid-cols-2">
      {(["name", "headline", "email", "phone", "location"] as const).map((key) => <Input key={key} placeholder={key[0].toUpperCase() + key.slice(1)} value={draft.basics[key]} onChange={(e) => patch({ basics: { ...draft.basics, [key]: e.target.value } })} />)}
    </div><Textarea rows={3} placeholder="Summary" value={draft.basics.summary} onChange={(e) => patch({ basics: { ...draft.basics, summary: e.target.value } })} /></section>
    <Section title="Experience" onAdd={() => add("experience", { company: "", role: "", location: "", start: "", end: "", bullets: [], tags: [] })}>{draft.experience.map((item, index) => <Card key={index} className="space-y-2"><div className="grid gap-2 sm:grid-cols-2"><Input placeholder="Role" value={item.role} onChange={(e) => update("experience", index, { role: e.target.value })} /><Input placeholder="Company" value={item.company} onChange={(e) => update("experience", index, { company: e.target.value })} /><Input placeholder="Location" value={item.location} onChange={(e) => update("experience", index, { location: e.target.value })} /><Input placeholder="Start - End" value={`${item.start}${item.end ? ` - ${item.end}` : ""}`} onChange={(e) => update("experience", index, { start: e.target.value })} /></div><Textarea placeholder="One bullet per line" value={item.bullets.join("\n")} onChange={(e) => update("experience", index, { bullets: lines(e.target.value) })} /><Remove onClick={() => remove("experience", index)} /></Card>)}</Section>
    <Section title="Projects" onAdd={() => add("projects", { name: "", description: "", url: "", bullets: [], tags: [] })}>{draft.projects.map((item, index) => <Card key={index} className="space-y-2"><Input placeholder="Name" value={item.name} onChange={(e) => update("projects", index, { name: e.target.value })} /><Input placeholder="URL" value={item.url} onChange={(e) => update("projects", index, { url: e.target.value })} /><Input placeholder="Description" value={item.description} onChange={(e) => update("projects", index, { description: e.target.value })} /><Textarea placeholder="One bullet per line" value={item.bullets.join("\n")} onChange={(e) => update("projects", index, { bullets: lines(e.target.value) })} /><Remove onClick={() => remove("projects", index)} /></Card>)}</Section>
    <Section title="Education" onAdd={() => add("education", { institution: "", degree: "", location: "", start: "", end: "", gpa: "", highlights: [], tags: [] })}>{draft.education.map((item, index) => <Card key={index} className="space-y-2"><div className="grid gap-2 sm:grid-cols-2"><Input placeholder="Institution" value={item.institution} onChange={(e) => update("education", index, { institution: e.target.value })} /><Input placeholder="Degree" value={item.degree} onChange={(e) => update("education", index, { degree: e.target.value })} /><Input placeholder="Start" value={item.start} onChange={(e) => update("education", index, { start: e.target.value })} /><Input placeholder="End" value={item.end} onChange={(e) => update("education", index, { end: e.target.value })} /></div><Textarea placeholder="Highlights" value={item.highlights.join("\n")} onChange={(e) => update("education", index, { highlights: lines(e.target.value) })} /><Remove onClick={() => remove("education", index)} /></Card>)}</Section>
    <Section title="Skills" onAdd={() => add("skills", { category: "", skills: [] })}>{draft.skills.map((item, index) => <div key={index} className="grid gap-2 sm:grid-cols-[1fr_2fr_auto]"><Input placeholder="Category" value={item.category} onChange={(e) => update("skills", index, { category: e.target.value })} /><Input placeholder="Comma-separated skills" value={item.skills.join(", ")} onChange={(e) => update("skills", index, { skills: csv(e.target.value) })} /><Remove onClick={() => remove("skills", index)} /></div>)}</Section>
    <Section title="Certifications" onAdd={() => add("certifications", { name: "", issuer: "", date: "" })}>{draft.certifications.map((item, index) => <div key={index} className="grid gap-2 sm:grid-cols-[2fr_1fr_1fr_auto]"><Input placeholder="Name" value={item.name} onChange={(e) => update("certifications", index, { name: e.target.value })} /><Input placeholder="Issuer" value={item.issuer} onChange={(e) => update("certifications", index, { issuer: e.target.value })} /><Input placeholder="Date" value={item.date} onChange={(e) => update("certifications", index, { date: e.target.value })} /><Remove onClick={() => remove("certifications", index)} /></div>)}</Section>
    <Section title="Awards" onAdd={() => add("awards", { title: "", issuer: "", date: "", description: "" })}>{draft.awards.map((item, index) => <div key={index} className="grid gap-2 sm:grid-cols-[2fr_1fr_1fr_2fr_auto]"><Input placeholder="Title" value={item.title} onChange={(e) => update("awards", index, { title: e.target.value })} /><Input placeholder="Issuer" value={item.issuer} onChange={(e) => update("awards", index, { issuer: e.target.value })} /><Input placeholder="Date" value={item.date} onChange={(e) => update("awards", index, { date: e.target.value })} /><Input placeholder="Description" value={item.description} onChange={(e) => update("awards", index, { description: e.target.value })} /><Remove onClick={() => remove("awards", index)} /></div>)}</Section>
    <Section title="Publications" onAdd={() => add("publications", { title: "", venue: "", date: "", url: "" })}>{draft.publications.map((item, index) => <div key={index} className="grid gap-2 sm:grid-cols-[2fr_1fr_1fr_2fr_auto]"><Input placeholder="Title" value={item.title} onChange={(e) => update("publications", index, { title: e.target.value })} /><Input placeholder="Venue" value={item.venue} onChange={(e) => update("publications", index, { venue: e.target.value })} /><Input placeholder="Date" value={item.date} onChange={(e) => update("publications", index, { date: e.target.value })} /><Input placeholder="URL" value={item.url} onChange={(e) => update("publications", index, { url: e.target.value })} /><Remove onClick={() => remove("publications", index)} /></div>)}</Section>
  </div>;
}

function Section({ title, onAdd, children }: { title: string; onAdd: () => void; children: ReactNode }) { return <section className="space-y-3"><div className="flex items-center justify-between"><CardTitle>{title}</CardTitle><Button variant="outline" size="sm" onClick={onAdd}>+ Add</Button></div>{children}</section>; }
function Remove({ onClick }: { onClick: () => void }) { return <Button type="button" variant="ghost" size="sm" onClick={onClick}>Remove</Button>; }
