export const COMMUNICATION_COPY = {
  title: "Communication",
  subtitle: "Review recruiting messages, keep what matters, and turn follow-ups into tasks.",
  search: "Search company or role",
  pendingTab: "Needs action",
  retainedTab: "Saved conversations",
  pendingEmptyTitle: "Nothing needs action",
  pendingEmpty: "When a message needs a reply or follow-up, it shows up here.",
  retainedEmptyTitle: "No saved conversations",
  retainedEmpty: "Keep a conversation to find it here later.",
  selectHint: "Select a conversation.",
  manualRecord: "Manual record",
  settings: "Settings",
  refresh: "Refresh",
  keep: "Keep",
  archive: "Archive",
  delete: "Delete",
  undo: "Undo",
} as const;
